defaults:
  - motif_dict
  - _self_

# General sampling params
args:
  fold_cond: False     # not supported


# Sampling dataset
dataset:
  # Lengths to sample. If not None, then use length-centric sampling
  # Uses `nres_lens` if specified, otherwise arange(min_len, max_len+1, step)
  nlens_cfg:
    nres_lens: null
    min_len:
    max_len:
    step_len:

  cath_codes: null  # Not supported

  # Number of samples per protein length or per cath code
  nsamples: 200

  # Maximum number of samples in each batch
  max_nsamples_per_batch: 5

  # Empirical (length, cath code) distribution
  empirical_distribution_cfg:
    # Path to the empirical (len, cath_code) distribution file
    len_cath_code_path: null

    # Level of cath codes to generate
    cath_code_level: null

    # Arguments for bucketizing the length distribution
    bucket_min_len: 50
    bucket_max_len: 274
    bucket_step_size: 25


# Sampling metrics
metric:
  # Designability metrics
  compute_designability: True
  designability_modes: ["ca", "bb3o"]  # Options: ca, bb3o
  designability_folding_models: ["esmfold"]  # List of folding models to use
  designability_motif_eval: True  # Enable motif-specific designability evaluation
  
  # Codesignability metrics
  compute_codesignability: True
  codesignability_modes: ["ca", "bb3o", "all_atom"]  # Options: ca, bb3o, all_atom
  codesignability_folding_models: ["esmfold"]  # List of folding models to use
  codesignability_motif_eval: True  # Enable motif-specific codesignability evaluation
  compute_co_sequence_recovery: False

  # Direct motif RMSD evaluation (generated structure vs ground truth motif)
  compute_motif_rmsd: True
  motif_rmsd_modes: ["ca", "bb3o", "all_atom"]  # Which atom models to compute for direct motif RMSD

  # Output management
  keep_folding_outputs: True  # Whether to keep folding model outputs (PDB files) after evaluation.
                               # If false (default), temporary directories containing predicted structures
                               # are deleted to save disk space. If true, all folding outputs are preserved
                               # in the temporary directories for debugging and further analysis.
                               # WARNING: Keeping outputs can consume significant disk space!

  # Novelty
  compute_novelty_pdb: False
  compute_novelty_afdb: False
  compute_novelty_afdb_rep_v4: False
  compute_novelty_afdb_rep_v4_geniefilters_maxlen512: False

  # FID-related metrics
  compute_fid: False
  metric_factory: null
